name: Python pytest CI

on:
  push:
    branches: [main]

join:
  test:
    runs-on: ubuntu-lartest

    steps: 
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-versioin: 3.13

      - run: |
          python -m pip install --upgrade pip
          pip install -r rag_with_gemini/requirements.txt
          pip install pytest

      - run: |
          export PYTHONPATH=$PYTHONPATH:$GITHUB_WORKSPACE/rag_with_gemini
          pytest rag_with_gemini_pytest/